baseURL = "/"
languageCode = "zh-cn"
title = "北京守望教会"

# theme = "hugo-PaperMod"
theme = "hugo-theme-stack"

# Copyright notice. This will display on the footer.

disablePathToLower = true
hasCJKLanguage = true
preserveTaxonomyNames = true
timeout = 20000
pluralizeListTitles = false
minify = true
defaultContentLanguage = "zh-cn"

ignoreLogs = ['warning-goldmark-raw-html']

[pagination]
pagerSize = 5

[services]
  [services.googleAnalytics]
    id = 'G-5D37ZNGXW6'

# Theme config
[params]

[params.widgets]

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"
[params.widgets.homepage.params]
limit = 5

[[params.widgets.homepage]]
type = "categories"
[params.widgets.homepage.params]
limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.page]]
type = "toc"

#   # The content you want to be listed on list pages.
mainSections = ["post"]

#   # The information will display on the post pages.
#   author = "守望"
#   description = "守望官网"
#   authorwebsite = "https://t5.shwchurch.org/"

#   # The path to your images
#   favicon = "images/logo.png"
#   logo = "images/logo.png"
#   avatar = ""
#   displayImg = "images/header_banner.jpg"
[params.homeInfoParams]
    Title = "基督教北京守望教会"

# [params.profileMode]
# enabled = true
# # title = "<Title>" # optional default will be site title
# # subtitle = "This is subtitle"
# imageUrl = "images/header_banner.jpg" # optional
# # imageTitle = "<title of image as alt>" # optional
# imageWidth = 120 # custom size
# imageHeight = 120 # custom size

[[params.homeInfoParams.buttons]]
    name = "首页"
    url = "/"

[[params.homeInfoParams.buttons]]
    name = "关于守望"
    url = "/2012/08/03/关于我们/"

[[params.profileMode.buttons]]
    name = "联系我们"
    url = "/2012/08/03/守望教会-联系我们/"

[[params.profileMode.buttons]]
    name = "所有分类"
    url = "/categories/"

[[params.socialIcons]]
    name = "logo"
    url = "images/logo.png"




# Social accounts config (This will display on the index page)
[[menu.shwchurch]]
    name = "主日敬拜程序"
    url = "/categories/主日敬拜程序/"
    weight = 1

[[menu.shwchurch]]
    name = "讲道"
    url = "/categories/讲道/"
    weight = 2

# [[menu.shwchurch]]
#     name = "户外敬拜"
#     url = "/tags/户外推荐资料/"
#     weight = 3

[[menu.shwchurch]]
    name = "所有分类"
    url = "/categories/"
    weight = 3

[Taxonomies]
  category = "categories"
  tag = "tags"


[markup]
  [markup.goldmark]
    duplicateResourceFiles = false
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      [markup.goldmark.extensions.cjk]
        eastAsianLineBreaks = true
        eastAsianLineBreaksStyle = 'simple'
        enable = true
        escapedSpace = true
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = true
        [markup.goldmark.extensions.extras.insert]
          enable = true
        [markup.goldmark.extensions.extras.mark]
          enable = true
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = []
          inline = []
      [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = true
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '&ldquo;'
        leftSingleQuote = '&lsquo;'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '&rdquo;'
        rightSingleQuote = '&rsquo;'
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true
      [markup.goldmark.renderHooks.link]
        enableDefault = true
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xhtml = false


